@echo off
title Auditor Verification UI

echo ===================================================
echo.
echo      STARTING AUDITOR VERIFICATION UI...
echo.
echo ===================================================
echo.
echo This will open the UI in your default web browser.
echo.
echo To use the UI, you will need an 'Audit Package' file
echo (e.g., process_log_0.json.audit_package.json)
echo generated by the Company Workflow tool.
echo.

:: Run the npm script that starts the Streamlit app
call npm run start:auditor_ui

echo.
echo UI has been stopped. You can close this window.
pause